version: '3.8'

volumes:
  database:
  wheeldir:
  ssl:

networks:
  database:
  reversed_proxy:

services:
  mysql:
    image: mariadb:10.5-focal
    # restart: always
    networks:
        - database
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
        - database:/var/lib/mysql
  nginx:
    image: nginx:1.21-alpine
    networks:
      - reversed_proxy
    ports:
      - ${PORT}:8080
    volumes:
      - ./backend/static:/static
      - ./dist:/dist
      - ./frontend/src/assets:/frontend/assets
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  node:
    image: node:17-alpine3.14
    working_dir: /src
    volumes:
      - ./:/src
    command: ["sleep", "infinity"]
  app:
    image: python:3.9-bullseye
    working_dir: /src
    networks:
      - database
      - reversed_proxy
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_CONFIG_MODULE}
      - AUTO_START=${AUTO_START}
    volumes:
      - ./:/src
      - ./scripts/command.sh:/usr/bin/cmd:ro
      - ./config/supervisor:/etc/supervisor
      - wheeldir:/wheeldir
    entrypoint: [/src/scripts/start.sh]
