version: '3.8'

services:
  app:
    image: app:python-3.9-bullseye
    build:
      context: ./_docker/app
      dockerfile: Dockerfile
      args:
        UID: ${U_ID}
        GID: ${G_ID}
    user: ${DOCKER_USER}
    restart: ${RESTART_POLICY}
    working_dir: /src
    networks:
      - reversed_proxy
    extra_hosts:
      - "docker.host:host-gateway"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_CONFIG_MODULE}
      - DJANGO_LOCAL_CONFIG=${DJANGO_LOCAL_CONFIG}
      - AUTO_START=${AUTO_START}
    volumes:
      - ./:/src
      - ./_docker/bashrc.sh:/.bashrc
      - ./_docker/supervisor:/etc/supervisor
      - ./_docker/app/command.sh:/usr/bin/cmd:ro
      - ./_docker/app/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/entrypoint.sh"]
