version: '3.8'

volumes:
  database:
  elastic_data:
    driver: local

networks:
  appnet:
    ipam:
      driver: default
      config:
        - subnet: 192.27.0.0/16

services:
  # Database
  mysql:
    image: mariadb:10.5-focal
    networks:
      appnet:
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
        # Database data
        - database:/var/lib/mysql
        # Miscelaneous
        - ./_docker/bashrc.sh:/.bashrc
  # Database admin
  adminer:
    image: adminer:4.8.1-standalone
    networks:
      appnet:
    ports:
      - 8080:8080
    volumes:
        # Miscelaneous
        - ./_docker/bashrc.sh:/.bashrc
  # Elastic search
  elasticsearch:
    image: app-elasticsearch:8.5.2
    build:
      context: ./_docker/elasticsearch/build
      dockerfile: Dockerfile
    container_name: elasticsearch
    networks:
      appnet:
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    mem_limit: 1.5g
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    networks:
      appnet:
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  # Node
  node:
    image: app-node:node-17
    build:
      context: ./_docker/node/build
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    working_dir: /src
    volumes:
      # Source folder
      - ./:/src
      # Miscelaneous
      - ./_docker/bashrc.sh:/.bashrc
    command: ["sleep", "infinity"]
  # Nginx / Nginx Unit / Python
  app:
    image: app-python:unit-python-3.10
    build:
      context: ./_docker/app/build
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    mem_limit: 8g
    depends_on:
      - adminer
      - mysql
    networks:
      appnet:
    working_dir: /src
    ports:
      - 9000:9000
    extra_hosts:
      - "docker.host:host-gateway"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_CONFIG_MODULE}
      - DJANGO_LOCAL_CONFIG=${DJANGO_LOCAL_CONFIG}
      - UNIT_AUTO_START=${UNIT_AUTO_START}
      - NGINX_AUTO_START=${NGINX_AUTO_START}
    volumes:
      # Source folder
      - ./:/src
      # Scripts
      - ./_docker/app/scripts/startup.sh:/startup.sh:ro
      - ./_docker/app/scripts/entrypoint.sh:/entrypoint.sh:ro
      # Supervisor
      - ./_docker/app/supervisor:/etc/supervisor:ro
      # Nginx / Unit
      - ./_docker/app/ssl/:/etc/nginx/ssl/
      - ./_docker/app/nginx/nginx.https.conf:/etc/nginx/sites-available/default:ro
      - ./_docker/app/nginx/server.configs:/etc/nginx/conf.d/server.configs:ro
      - ./_docker/app/unit/:/docker-entrypoint.d/
      # Miscelaneous
      - ./_docker/app/scripts/command.py:/usr/local/bin/cmd:ro
      - ./_docker/app/scripts/pip-install.sh:/usr/local/bin/pip-install:ro
      - ./_docker/bashrc.sh:/.bashrc
    entrypoint: ["/entrypoint.sh"]