version: '3.8'

networks:
  reversed_proxy:

services:
  nginx:
    image: nginx:1.21-alpine
    restart: ${RESTART_POLICY}
    networks:
      - reversed_proxy
    ports:
      - ${PORT}:8080
    volumes:
      - ./backend/static:/static
      - ./dist:/dist
      - ./frontend/src/assets:/frontend/assets
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - "app"
  app:
    user: ${DOCKER_USER}
    image: python:3.9-bullseye
    restart: ${RESTART_POLICY}
    working_dir: /src
    networks:
      - reversed_proxy
    extra_hosts:
      - "docker.host:host-gateway"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_CONFIG_MODULE}
      - DJANGO_LOCAL_CONFIG=${DJANGO_LOCAL_CONFIG}
      - AUTO_START=${AUTO_START}
    volumes:
      - ./:/src
      - ./config/_bashrc.sh:/.bashrc
      - ./config/supervisor:/etc/supervisor
      - ./scripts/command.sh:/usr/bin/cmd:ro
    entrypoint: [/src/scripts/start.sh]
