# Generated by Django 4.0.3 on 2022-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('priority', models.SmallIntegerField(choices=[(4, 'Urgent'), (3, 'High'), (2, 'Medium'), (1, 'Low')], default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done')], default='in_progress', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Todo Item',
                'verbose_name_plural': 'Todo Items',
            },
        ),
    ]
